[packages]
glib = "*"
nspr = "*"
nss = "*"
dbus = "*"
atk = "*"
atk-bridge = "*"
at-spi2-core = "*"
libx11 = "*"
libxcomposite = "*"
libxdamage = "*"
libxext = "*"
libxfixes = "*"
libxrandr = "*"
libgbm = "*"
libxcb = "*"
libxkbcommon = "*"
libasound2 = "*"
